flaskrental/main/routes.py
from flask import Blueprint
from flask import render_template, request, Blueprint, url_for
#from flaskrental.models import Product

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    image_file = url_for('static', filename='pictures/Neoleehospitalbed1.jpg')
    return render_template('home.html', image_file=image_file)

@main.route("/contact")
def contact():
    return render_template('contact.html')


@main.route("/sample")
def sample():
    return render_template('sample.html')

flaskrental/rentalusers/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required
from flaskrental import db, bcrypt
from flaskrental.models import User
from flaskrental.rentalusers.forms import (RegistrationForm, LoginForm, UpdateAccountForm, 
                                     RequestResetForm, ResetPasswordForm)
from flaskrental.rentalusers.utils import send_reset_email


rentalusers = Blueprint('rentalusers', __name__)

@rentalusers.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created! You are now able to login', 'success')
        return redirect(url_for('main.login'))
    else:
        return render_template('register.html', title='Register', form=form)

@rentalusers.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@rentalusers.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@rentalusers.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your Account has been updated!', 'success')
        return redirect(url_for('rentalusers.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)


@rentalusers.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        flash(f'Please Log out first before resetting password')
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('rentalusers.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@rentalusers.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        flash(f'Please Log out first before resetting password')
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash(f'That is an invalid or expired token', 'warning')
        return redirect(url_for('rentalusers.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated', 'success')
        return redirect(url_for('rentalusers.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskrental/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <div class="media-body">
                <h2 class="account-heading">Username: {{ current_user.username }}</h2>
                <h2 class="text-secondary">Email: {{ current_user.email }}</h2>
            </div>
        </div>
        </br>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Account Info Here</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

flaskrental/templates/contact.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h2 class="elementor-heading-title elementor-size-default">Contact Us</h2>
        <h2> 012-34567890 </h2>
    </div>
{% endblock %}

flaskrental/templates/create_product.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
<form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Upload a new Product</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}

                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span> {{ error }} </span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                    {{ form.description(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.description.errors %}
                            <span> {{ error }} </span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.image_file.label() }}
                {{ form.image_file(class="form-control-file") }}
                {% if form.image_file.errors %}
                    {% for error in form.image_file.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </div>
</form>

<br>
<div class="row mx-3">
    {% for product in products %}
        <div class="card mx-3" style="width: 18rem;">
            <img class="card-img-top" src="{{ url_for('static', filename='product.image_file') }}">
            <div class="card-body">
                <h5 class="card-title">
                    Something
                </h5>
                <p class="card-text">
                    Something
                </p>
            </div>
        </div>
    {% endfor %}
    
{% endblock %}

flaskrental/templates/home.html
{% extends "layout.html" %}
{% block content %}


<body>
  <main>
    <section>
        <div class="container">
          <h2>Featured Products</h2>
          </br>
          <div class="row">
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
          <div class="row">
          <div class="panel-block-row col-md-12"><img style="max-width: 100%; width: 100%;" src="static/pictures/bed_manual_2_func.jpg"></div>
          <div class="panel-block-row col-md-12">
          <p>&nbsp;</p>
          </div>
          </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
          <div class="row">
          <div class="panel-block-row col-md-12"><img style="max-width: 100%; width: 100%;" src="static/pictures/bed_manual_3_func.jpg"></div>
          <div class="panel-block-row col-md-12">
          <p>&nbsp;</p>
          </div>
          </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
          <div class="row">
          <div class="panel-block-row col-md-12"><img style="max-width: 100%; width: 100%;" src="static/pictures/bed_manual_5_func.jpg"></div>
          <div class="panel-block-row col-md-12">
          <p>&nbsp;</p>
          </div>
          </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
          <div class="row">
          <div class="panel-block-row col-md-12"><img style="max-width: 100%; width: 100%;" src="static/pictures/bed_hopkins_2_func_man.png"></div>
          <div class="panel-block-row col-md-12">
          <p>&nbsp;</p>
          </div>
          </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
          <div class="row">
          <div class="panel-block-row col-md-12"><img style="max-width: 100%; width: 100%;" src="static/pictures/bed_hopkins_3_func_elec.png"></div>
          <div class="panel-block-row col-md-12">
          <p>&nbsp;</p>
          </div>
          </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
          <div class="row">
          <div class="panel-block-row col-md-12"><img style="max-width: 100%; width: 100%;" src="static/pictures/mattress_hopkin_pvc.png"></div>
          <div class="panel-block-row col-md-12">
          <p>&nbsp;</p>
          </div>
          </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
          <div class="row">
          <div class="panel-block-row col-md-12"><img style="max-width: 100%; width: 100%;" src="static/pictures/oxy_philips_everflow.jpg"></div>
          <div class="panel-block-row col-md-12">
          <p>&nbsp;</p>
          </div>
          </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
          <div class="row">
          <div class="panel-block-row col-md-12"><img style="max-width: 100%; width: 100%;" src="static/pictures/bubble_ripple_mattress_1.jpg"></div>
          <div class="panel-block-row col-md-12">
          <p>&nbsp;</p>
          </div>
          </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
          <div class="row">
          <div class="panel-block-row col-md-12"><img style="max-width: 100%; width: 100%;" src="static/pictures/ripple_mattress_1.jpg"></div>
          <div class="panel-block-row col-md-12">
          <p>&nbsp;</p>
          </div>
          </div>
          </div>
          </div>
          </div>    
    </section>
  </main>
</body>
{% endblock content %}

flaskrental/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href="{{ url_for('static', filename='main.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">
</head>
  <body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
              <img class ="logo" width="150" height="65" src="static/pictures/logo_sample2.jpg">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home')}}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.contact')}}">Contact Us</a>
              </div>
                <div class="StylableButton2545352419__container">
                  <a class="btnWhatsapp" href="https://wa.me/60126058565?text=" target="_blank"> <span>+6012-605-8565<br>
                      On Whatsapp</span> <img alt="" class="img-fluid-header" src="https://cdn1.npcdn.net/img/1664529335menu-whatapp-icon.png"> </a>
                     </div>
                     <div class="StylableButton2545352419__container">
                     <a class="btnWhatsapp" href="" target="_blank"> <span>Chat With Us<br>
                      On Messenger</span> <img alt="" class="img-fluid-header" src="https://cdn1.npcdn.net/userfiles/18414/image/Facebook_Messenger_logo_2013_svg.png"> </a>
                     </div>
                        <defs>
                            <clipPath id="48733500-4383-46ad-8060-382775114be0">
                                <path d="M106.332 106.332H703v596.672H106.332zm0 0"></path>
                            </clipPath>
                        </defs>
                        <g clip-path="url(#48733500-4383-46ad-8060-382775114be0)">
                            <path d="M405.016 106.332c-164.262 0-297.985 133.606-298.043 297.871-.032 52.504 13.722 103.766 39.797 148.934l-40.438 149.867 156.102-36.883c43.527 23.746 92.527 36.211 142.41 36.242h.117c164.23 0 297.894-133.636 297.984-297.87.059-79.626-30.902-154.49-87.168-210.817-56.27-56.297-131.043-87.313-210.761-87.344zM404.96 166c63.723.027 123.61 24.875 168.629 69.863 45.02 45.047 69.75 104.907 69.687 168.57-.058 131.387-106.93 238.262-238.375 238.262-39.77-.03-79.164-10.015-113.859-28.96l-20.102-10.954-22.199 5.246-58.738 13.868 14.336-53.258 6.469-23.89-12.356-21.442c-20.824-36.04-31.844-77.246-31.812-119.102C166.699 272.875 273.6 166 404.96 166zM299.55 266.688c-4.98 0-13.04 1.863-19.871 9.324-6.832 7.425-26.102 25.418-26.102 62.054 0 36.637 26.688 72.051 30.414 77.032 3.7 4.953 51.516 82.507 127.203 112.343 62.887 24.79 75.66 19.899 89.325 18.645 13.664-1.223 44.082-17.977 50.285-35.367 6.207-17.395 6.222-32.356 4.37-35.43-1.847-3.101-6.816-4.953-14.277-8.68-7.425-3.73-44.035-21.707-50.867-24.183-6.832-2.477-11.828-3.73-16.781 3.73-4.953 7.457-19.184 24.18-23.54 29.133-4.355 4.984-8.683 5.652-16.14 1.922-7.46-3.758-31.441-11.64-59.902-37-22.137-19.719-37.074-44.05-41.43-51.508-4.324-7.43-.406-11.512 3.325-15.21 3.34-3.34 7.398-8.696 11.128-13.052 3.7-4.355 4.98-7.457 7.457-12.41 2.477-4.953 1.211-9.324-.64-13.054-1.852-3.727-16.336-40.5-22.957-55.239-5.578-12.379-11.473-12.668-16.781-12.875-4.329-.18-9.266-.175-14.22-.175zm0 0"></path>
                        </g>
                    </g>
                </svg>
                </div></span></div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link-left" href="{{ url_for('rentalusers.account')}}">Account</a>
                <a class="nav-item nav-link-right" href="{{ url_for('rentalusers.logout')}}">Logout</a>
                {% else %}
                <a class="nav-item nav-link-left" href="{{ url_for('rentalusers.login')}}">Login</a>
                <a class="nav-item nav-link-right" href="{{ url_for('rentalusers.register')}}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <br><br><br><br>
    {%  with messages = get_flashed_messages(with_categories=true)  %}
      {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{ message }}
        </div>
        {% endfor %}
      {% endif %}
    {%  endwith  %}

    {% block content %}

    {% endblock %}
    <div class="bgManually_footer_top">
        <div class="site-footer">
          <div class="secManually_footer_top_ctrl_width">
            <div class="row">
              <div class="col-md-4 secManually_footer_top_left_ebox">
                <div class="secManually_footer_top_left_box">
                  <div class="secManually_footer_top_left_logo_imgx">
                    <img class="logo" alt="" class="img-fluid" src="static/pictures/logo_sample2.jpg"></div>
                  <ul class="secManually_footer_top_left_payment_imgx">
                    <li>
                      <img alt="" class="img-fluid" src="https://cdn1.npcdn.net/images/1664529432footer-payment1.webp?md5id=f743456c2e829c48b24c85ebd8024eba&amp;new_width=1600&amp;new_height=1600&amp;size=max&amp;type=8&amp;w=1686755673&amp;off_wm=1&amp;from=png"></li>
                    <li>
                      <img alt="" class="img-fluid" src="https://cdn1.npcdn.net/images/1664529443footer-payment2.webp?md5id=f743456c2e829c48b24c85ebd8024eba&amp;new_width=1600&amp;new_height=1600&amp;size=max&amp;type=8&amp;w=1686755673&amp;off_wm=1&amp;from=png"></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-4 secManually_footer_top_middle_ebox">
                <div class="secManually_footer_top_middle_box">
                  <div class="secManually_footer_top_middle_title">
                    Product Category</div>
                  <ul class="secManually_footer_top_middle_menu">
                    <li>
                      <a href="">Wheelchairs</a></li>
                    <li>
                      <a href="">Hospital Beds</a></li>
                    <li>
                      <a href="/">Anti Bedsore</a></li>
                    <li>
                      <a href="/">Hospital Furniture</a></li>
                    <li>
                      <a href="/">Incontinence Care</a></li>
                    <li>
                      <a href="/">Medical Devices</a></li>
                    <li>
                      <a href="">Walking Aids</a></li>
                    <li>
                      <a href="">Rehabilitation</a></li>
                    <li>
                      <a href="">Special Needs</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-4 secManually_footer_top_right_ebox">
                <div class="secManually_footer_top_right_box">
                  <div class="secManually_footer_top_right_title">
                    Contact Us</div>
                  <div class="secManually_footer_top_right_content">
                    <div class="secManually_footer_top_right_branch">
                    <ul class="secManually_footer_top_right_contact">
                      <li>
                        <a href="https://wa.me/60126058565?text=" target="_blank"> <i class="fab fa-whatsapp"></i> <span>+6012-605-8565</span> </a></li>
                      <li>
                        <a href=""> <i class="fas fa-envelope"></i> <span>Our Email Link</span> </a></li>
                      <li>
                        <a href="" target="_blank"> <i class="fas fa-globe"></i> <span>Our Website Link</span> </a></li>
                      <li>
                        <i class="far fa-clock"></i> <span>Monday-Sunday (10.00am-6.00pm)</span></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

flaskrental/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class = "content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                    </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('rentalusers.reset_request')}}">Forgot Password?</a>
                </small>
            </div>
            
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't have an Account? <a class="ml-2" href="{{ url_for('rentalusers.register') }}">Sign Up</a>
        </small>
    </div>
{% endblock %}

flaskrental/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class = "content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Become a Member Today!</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('rentalusers.login') }}">Sign In</a>
        </small>
    </div>
{% endblock %}

flaskrental/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class = "content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

flaskrental/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class = "content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}